-- Bloque 3: índices, triggers, RLS (InsForge)
CREATE INDEX IF NOT EXISTS idx_prendas_categoria ON public.prendas(categoria_id);
CREATE INDEX IF NOT EXISTS idx_costos_talla ON public.costos(talla_id);
CREATE INDEX IF NOT EXISTS idx_costos_prenda ON public.costos(prenda_id);
CREATE INDEX IF NOT EXISTS idx_costos_sucursal ON public.costos(sucursal_id);
CREATE INDEX IF NOT EXISTS idx_insumos_presentacion_id ON public.insumos(presentacion_id);
CREATE INDEX IF NOT EXISTS idx_prenda_talla_insumos_prenda ON public.prenda_talla_insumos(prenda_id);

DROP TRIGGER IF EXISTS update_categorias_prendas_updated_at ON public.categorias_prendas;
CREATE TRIGGER update_categorias_prendas_updated_at BEFORE UPDATE ON public.categorias_prendas FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_tallas_updated_at ON public.tallas;
CREATE TRIGGER update_tallas_updated_at BEFORE UPDATE ON public.tallas FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_prendas_updated_at ON public.prendas;
CREATE TRIGGER update_prendas_updated_at BEFORE UPDATE ON public.prendas FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_insumos_updated_at ON public.insumos;
CREATE TRIGGER update_insumos_updated_at BEFORE UPDATE ON public.insumos FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trigger_costos_updated_at ON public.costos;
CREATE TRIGGER trigger_costos_updated_at BEFORE UPDATE ON public.costos FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_prenda_talla_insumos_updated_at ON public.prenda_talla_insumos;
CREATE TRIGGER update_prenda_talla_insumos_updated_at BEFORE UPDATE ON public.prenda_talla_insumos FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_compras_insumos_updated_at ON public.compras_insumos;
CREATE TRIGGER update_compras_insumos_updated_at BEFORE UPDATE ON public.compras_insumos FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_costo_ubicaciones_updated_at ON public.costo_ubicaciones;
CREATE TRIGGER update_costo_ubicaciones_updated_at BEFORE UPDATE ON public.costo_ubicaciones FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_insumo_ubicaciones_updated_at ON public.insumo_ubicaciones;
CREATE TRIGGER update_insumo_ubicaciones_updated_at BEFORE UPDATE ON public.insumo_ubicaciones FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_presentaciones_updated_at ON public.presentaciones;
CREATE TRIGGER update_presentaciones_updated_at BEFORE UPDATE ON public.presentaciones FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_ubicaciones_almacenamiento_updated_at ON public.ubicaciones_almacenamiento;
CREATE TRIGGER update_ubicaciones_almacenamiento_updated_at BEFORE UPDATE ON public.ubicaciones_almacenamiento FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_sucursales_updated_at ON public.sucursales;
CREATE TRIGGER update_sucursales_updated_at BEFORE UPDATE ON public.sucursales FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.categorias_prendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tallas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insumos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.costos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.presentaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ubicaciones_almacenamiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sucursales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prenda_talla_insumos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compras_insumos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.costo_ubicaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insumo_ubicaciones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS categorias_prendas_all ON public.categorias_prendas;
CREATE POLICY categorias_prendas_all ON public.categorias_prendas FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS tallas_all ON public.tallas;
CREATE POLICY tallas_all ON public.tallas FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS prendas_all ON public.prendas;
CREATE POLICY prendas_all ON public.prendas FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS insumos_all ON public.insumos;
CREATE POLICY insumos_all ON public.insumos FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS costos_all ON public.costos;
CREATE POLICY costos_all ON public.costos FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS presentaciones_all ON public.presentaciones;
CREATE POLICY presentaciones_all ON public.presentaciones FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS ubicaciones_all ON public.ubicaciones_almacenamiento;
CREATE POLICY ubicaciones_all ON public.ubicaciones_almacenamiento FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS sucursales_all ON public.sucursales;
CREATE POLICY sucursales_all ON public.sucursales FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS prenda_talla_insumos_all ON public.prenda_talla_insumos;
CREATE POLICY prenda_talla_insumos_all ON public.prenda_talla_insumos FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS compras_insumos_all ON public.compras_insumos;
CREATE POLICY compras_insumos_all ON public.compras_insumos FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS costo_ubicaciones_all ON public.costo_ubicaciones;
CREATE POLICY costo_ubicaciones_all ON public.costo_ubicaciones FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS insumo_ubicaciones_all ON public.insumo_ubicaciones;
CREATE POLICY insumo_ubicaciones_all ON public.insumo_ubicaciones FOR ALL USING (true) WITH CHECK (true);
